---
- hosts: all
  become: yes
  vars:
    server_ip: "{{ ansible_default_ipv4.address }}"
    my_name: yossef
    server_name: "{{ ansible_nodename }}"

  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy website files to the server's document root
      template:
        src: index.html
        dest: /var/www/html

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
