---
- hosts: webservers
  remote_user: ubuntu
  gather_facts: no
  become: yes
  # vars:
  #  my_name: yossef
  roles:
   - iti_webserver


- hosts: jenkins_agents
  remote_user: ec2-user
  gather_facts: no
  become: yes
  
  roles:
   - jenkins_role